### ISSUE TITLE
create invoice page bakcground color

### ISSUE THREAD

**Issue by tenmusu007** [tenmusu007/invoice-app#66]
- create page style need to be fixed 
- /mylist/invociepage page needs to be fixed

**Comment by tenmusu007** [comment]
I fixed this issue on husky branch. When I marge husky branch, it would be solved

**Comment by tenmusu007** [comment]
なんかdevマージしたら消えた

**Comment by tenmusu007** [comment]
@Ayut0 ここ私もうわからないのでお兄さん託していいすか？
<img width="1431" alt="Screenshot 2023-04-30 at 1 48 37 PM" src="https://user-images.githubusercontent.com/95890096/235375565-c46efff9-0159-48ee-9fc2-6ee7487ed55a.png">

**Comment by Ayut0** [comment]
Done
